# Generated by Django 5.1.7 on 2025-03-12 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_phoneverification_user'),
    ]

    operations = [
    ]
